[package]
name = "svgbob"
version = "0.6.7"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
description = "Transform your ascii diagrams into happy little SVG"
repository = "https://github.com/ivanceras/svgbob"
documentation = "https://docs.rs/svgbob"
keywords = ["ascii","plain","text", "svg", "bob"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
nalgebra = "0.30.1"
parry2d = "0.8.0"
lazy_static = "1.3.0"
sauron = { version = "0.51", default-features = false}
#sauron = { path = "../../../sauron", default-features = false}
unicode-width = "0.1.9"
itertools = "0.10.3"
pom = { version = "3.2.0" }
log = "0.4.14"
indexmap = "1.9.1"



[features]
# This affects the rendering of text nodes
# if the svg is rendered statically, characters such as '<' needed to be escaped
# while if it is rendered in the dom, no escaping is needed.
with-dom = ["sauron/with-dom"]

