[package]
name = "svgbob_server"
version = "0.7.3"
authors = ["Jovansonlee Cesar <ivanceras@gmail.com>"]
description = "Transform your ascii diagrams into happy little SVG"
repository = "https://github.com/ivanceras/svgbob"
documentation = "https://docs.rs/svgbob"
keywords = ["ascii", "svg", "convert", "bob"]
license = "Apache-2.0"
edition = "2021"


[dependencies]
svgbob = { path = "../svgbob", version = "0.7" }
axum = "0.6.19"
tokio = { version = "1.0", features = ["full"] }
